version: '2.1'
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
      - 5000:5000
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./data/certs:/certs
      - ./conf/auth:/auth
    restart: always
    environment:
      - DOMAIN={DOCKER_REGISTRY_DOMAIN_NAME}
    command: "sh -c '/usr/sbin/nginx && nc -v -l -p 12345 -e nginx -s reload'"
  certbot:
    build:
      context: certbot
      dockerfile: Dockerfile
    container_name: certbot
    ports:
      - 81:80
    volumes:
      - ./data/certs:/certs
      - ./data/certbot/letsencrypt:/etc/letsencrypt
      - ./data/certbot/var_log_letsencrypt:/var/log/letsencrypt
    environment:
      - LOGFILE=/var/log/letsencrypt/certrenewal.log
      - DEBUG=false
      - STAGING=false
      - HEALTH_CHECK_URL=${DOCKER_REGISTRY_DOMAIN_NAME}:80
      - DOMAINS=${DOCKER_REGISTRY_DOMAIN_NAME}
      - EMAIL=${DOCKER_REGISTRY_CERT_EMAIL_ADDRESS}
      - RENEWED_CERTS_HOOK=echo "1" | nc nginx 12345
  registry:
    image: registry:2
    ports:
      - 127.0.0.1:5001:5000
    volumes:
      - ./data/registry:/var/lib/registry
    restart: always
